Add map section
Weaverse/weaverse pull request #38
Opened 2023-10-19 10:21 UTC by dangthang1903

2023-10-26 02:31 UTC, hta218 requested changes

2023-10-26 02:31 UTC, hta218 commented on app/sections/map.tsx
> +            <path fill-rule="evenodd" clip-rule="evenodd" d="M171.168 30.3128C171.673 30.4812 172.184 30.6519 172.702 30.8246L184.222 34.6645C188.66 36.1436 192.55 37.44 195.636 38.8757C198.972 40.42
Put your icon markup in `app/components/Icon.tsx` file, then import here to use

2023-10-26 02:31 UTC, hta218 commented on app/sections/map.tsx
> +  enableNewtab: boolean;
change to `openInNewTab`

2023-10-31 09:39 UTC, hta218 requested changes
Please resolve conflicts

2023-10-31 09:51 UTC, dangthang1903 commented
em đã sửa conflict anh check lại giúp em ạ

2023-10-31 23:32 UTC, hta218 approved these changes

2023-10-31 23:32 UTC, merged