Add promotion grid section
Weaverse/weaverse pull request #39
Opened 2023-10-26 03:13 UTC by dangthang1903

2023-10-26 03:33 UTC, hta218 requested changes

2023-10-26 03:33 UTC, hta218 commented on app/sections/promotion-grid/item.tsx
> +  backgroundImage: {
Import `WeaverseImage` type from `@weaverse/hydrogen` instead of defining type for `backgroundImage`

2023-10-26 03:33 UTC, hta218 commented on app/sections/promotion-grid/item.tsx
> +            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none" className='w-24 h-24 text-white'>
Add icon in `app/components/Icon.tsx` file then import here to use

2023-10-26 03:33 UTC, hta218 commented on app/sections/promotion-grid/item.tsx
> +  enableNewtab: boolean;
Change to `openInNewTab`

2023-10-31 23:33 UTC, hta218 requested changes
Please remove the text size configs & resolve conflicts

2023-11-01 04:32 UTC, dangthang1903 commented
em đã sửa lại code, anh check lại PR giúp em ạ

2023-11-06 08:22 UTC, hta218 approved these changes

2023-11-06 08:22 UTC, merged