Update more sections and add component button
Weaverse/weaverse pull request #58
Opened 2023-12-05 07:16 UTC by dangthang1903

2023-12-05 08:30 UTC, hta218 requested changes
Good update bro!
Please also make these changes:
- Add a config group to **Theme Settings** to set the global config for Buttons (Use `Buttons` as the group name) 
- Add color settings for 3 styles of Buttons
- Make your button component use colors from the **Theme Settings**

2023-12-05 08:30 UTC, hta218 commented on app/sections/CountDown/ButtonItems.tsx
> +  type: 'Button-CountDown-items',
Use lowercase text for all items `type`. `Button-CountDown-items` --> `countdown-buttons`

2023-12-05 08:30 UTC, hta218 commented on app/sections/PromotionGrid/ButtonItems.tsx
> +  type: 'Button-Promotion-items',
`Button-Promotion-items` -> `promotion-buttons`

2023-12-05 08:30 UTC, hta218 commented on app/sections/shared/Button.tsx
> +type ButtonStyle = '1' | '2' | '3';
Change the style to meaningful value: `primary` | `secondary` | `subtle`, instead of `1`, `2`, and `3`

2023-12-05 08:30 UTC, hta218 commented on app/sections/shared/Button.tsx
> +          type: 'toggle-group',
Button text-align should always be `center`, so I think there is no need for the `alignment` setting for a button

2023-12-07 10:28 UTC, hta218 commented
Any progress on this @dangthang1903 ?

2023-12-11 04:06 UTC, dangthang1903 commented
em update lại anh check giúp em ạ

2023-12-11 05:02 UTC, hta218 approved these changes

2023-12-11 05:03 UTC, merged